[workspace]
members = [".", "protobufs"]

[package]
name = "hedera"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[features]
ffi = []

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
time = { version = "0.3.9", features = ["serde"] }
tokio = { version = "1.18.1", features = ["rt-multi-thread"] }
hedera-proto = { path = "./protobufs", features = ["serde", "time_0_3", "fraction"] }
serde_json = "1.0.79"
serde_with = { version = "2.0.0", features = ["hex", "base64", "time_0_3"] }
tonic = "0.8.0"
async-trait = "0.1.53"
prost = "0.11.0"
hex = "0.4.3"
paste = "1.0.7"
parking_lot = "0.12.0"
http = "0.2.7"
rand = "0.8.5"
log = "0.4.17"
backoff = "0.4.0"
ed25519-dalek = { version = "1.0.1", features = ["rand", "serde"] }
sha2 = "0.10.2"
itertools = "0.10.3"
once_cell = "1.10.0"
futures-util = "0.3.21"
k256 = "0.11.0"
pkcs8 = "0.9.0"
async-stream = "0.3.3"
futures-core = "0.3.21"
fraction = { version = "0.11.0", features = ["with-serde-support"] }
either = { version = "1.7.0", features = ["serde"] }
base64 = "0.13.0"
rust_decimal = "1.26.1"
derive_more = "0.99.17"

[dev-dependencies]
anyhow = "1.0.57"
assert_matches = "1.5.0"
pretty_env_logger = "0.4.0"
tokio = { version = "1.18.1", features = ["full"] }
clap = { version = "3.1.18", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3"

[build-dependencies]
anyhow = "1.0.57"
cbindgen = "0.24.3"

[profile.release]
strip = true
lto = "fat"
overflow-checks = false
debug = 0
opt-level = "z"
codegen-units = 1
panic = "abort"

[patch.crates-io]
curve25519-dalek = { git = "https://github.com/launchbadge/curve25519-dalek", branch = "lb-update" }
ed25519-dalek = { git = "https://github.com/launchbadge/ed25519-dalek", branch = "lb-update" }
